spring:
  datasource:
    url: jdbc:mysql://(RDS 엔드포인트):3306/(스키마명)?userSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&autoReconnect=True
    username : root
    password : password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

